2019-03-26 15:38:30,621 - root - INFO - ********TEST START********
2019-03-26 15:38:30,622 - root - INFO - ********TEST START********
2019-03-26 15:38:30,627 - root - INFO - testCall测试开始前准备
2019-03-26 15:38:30,627 - root - INFO - testCall测试开始前准备
2019-03-26 15:38:32,642 - selenium.webdriver.remote.remote_connection - INFO - Could not connect to port 4723 on host localhost
2019-03-26 15:38:32,642 - selenium.webdriver.remote.remote_connection - INFO - Could not get IP address for host: localhost
2019-03-26 15:38:32,880 - root - INFO - *********TEST END*********
2019-03-26 15:38:32,880 - root - INFO - Doesn't send report email to developer.
2019-03-26 15:38:34,653 - urllib3.connectionpool - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000B14939EB00>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /wd/hub/session
2019-03-26 15:38:36,677 - urllib3.connectionpool - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000B14939EE80>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /wd/hub/session
2019-03-26 15:38:38,681 - urllib3.connectionpool - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000B14939EBA8>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /wd/hub/session
2019-03-26 15:38:40,682 - root - INFO - *********TEST END*********
2019-03-26 15:38:40,682 - root - INFO - Doesn't send report email to developer.
