2019-03-26 15:37:39,363 - root - INFO - ********TEST START********
2019-03-26 15:37:39,364 - root - INFO - testCall测试开始前准备
2019-03-26 15:37:39,370 - root - INFO - ********TEST START********
2019-03-26 15:37:39,374 - root - INFO - testCall测试开始前准备
2019-03-26 15:37:41,377 - selenium.webdriver.remote.remote_connection - INFO - Could not connect to port 4723 on host localhost
2019-03-26 15:37:41,377 - selenium.webdriver.remote.remote_connection - INFO - Could not get IP address for host: localhost
2019-03-26 15:37:41,598 - root - INFO - *********TEST END*********
2019-03-26 15:37:41,599 - root - INFO - Doesn't send report email to developer.
2019-03-26 15:37:43,387 - urllib3.connectionpool - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000FB72EBEA90>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /wd/hub/session
2019-03-26 15:37:45,394 - urllib3.connectionpool - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000FB72EBED68>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /wd/hub/session
2019-03-26 15:37:47,398 - urllib3.connectionpool - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000FB72EBEB38>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /wd/hub/session
2019-03-26 15:37:49,406 - root - INFO - *********TEST END*********
2019-03-26 15:37:49,406 - root - INFO - Doesn't send report email to developer.
